/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuIdRouteImport } from './routes/menu.$id'
import { Route as TrackOrderIdRouteImport } from './routes/track-order.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIdRoute = MenuIdRouteImport.update({
  id: '/menu/$id',
  path: '/menu/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track-order/$id',
  path: '/track-order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-success': typeof OrderSuccessRoute
  '/menu/$id': typeof MenuIdRoute
  '/track-order/$id': typeof TrackOrderIdRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-success': typeof OrderSuccessRoute
  '/menu/$id': typeof MenuIdRoute
  '/track-order/$id': typeof TrackOrderIdRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-success': typeof OrderSuccessRoute
  '/menu/$id': typeof MenuIdRoute
  '/track-order/$id': typeof TrackOrderIdRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/menu/$id'
    | '/track-order/$id'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/menu/$id'
    | '/track-order/$id'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/menu/$id'
    | '/track-order/$id'
    | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  MenuIdRoute: typeof MenuIdRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$id': {
      id: '/menu/$id'
      path: '/menu/$id'
      fullPath: '/menu/$id'
      preLoaderRoute: typeof MenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order/$id': {
      id: '/track-order/$id'
      path: '/track-order/$id'
      fullPath: '/track-order/$id'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  MenuIdRoute: MenuIdRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  MenuIndexRoute: MenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
